[
  "up_blocks.1.attentions.0.transformer_blocks.0.attn1",
  "up_blocks.1.attentions.1.transformer_blocks.0.attn1",
  "up_blocks.1.attentions.2.transformer_blocks.0.attn1",
  "up_blocks.2.attentions.0.transformer_blocks.0.attn1",
  "up_blocks.2.attentions.1.transformer_blocks.0.attn1",
  "up_blocks.2.attentions.2.transformer_blocks.0.attn1",
  "up_blocks.3.attentions.0.transformer_blocks.0.attn1",
  "up_blocks.3.attentions.1.transformer_blocks.0.attn1",
  "up_blocks.3.attentions.2.transformer_blocks.0.attn1",
]
