[
  "down_blocks.0.attentions.0.transformer_blocks.0.attn1",
  "down_blocks.0.attentions.1.transformer_blocks.0.attn1",
  "down_blocks.1.attentions.0.transformer_blocks.0.attn1",
  "down_blocks.1.attentions.1.transformer_blocks.0.attn1",
  "down_blocks.2.attentions.0.transformer_blocks.0.attn1",
  "down_blocks.2.attentions.1.transformer_blocks.0.attn1",
]
