multiview_feature_extraction:
  animation_artifact_tag: "backflip:latest"
  out_artifact_name: "deadpool-mv-features"
  prompt: "Deadpool does a backflip"
  num_inference_steps: 30
  num_views: 10
  save_steps:
    [
      0,
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21,
      22,
      23,
      24,
      25,
      26,
      27,
      28,
      29,
    ]
  module_paths:
    [
      "down_blocks.0.attentions.0.transformer_blocks.0.attn1",
      "down_blocks.0.attentions.1.transformer_blocks.0.attn1",
      "down_blocks.1.attentions.0.transformer_blocks.0.attn1",
      "down_blocks.1.attentions.1.transformer_blocks.0.attn1",
      "down_blocks.2.attentions.0.transformer_blocks.0.attn1",
      "down_blocks.2.attentions.1.transformer_blocks.0.attn1",
      "up_blocks.1.attentions.0.transformer_blocks.0.attn1",
      "up_blocks.1.attentions.1.transformer_blocks.0.attn1",
      "up_blocks.1.attentions.2.transformer_blocks.0.attn1",
      "up_blocks.2.attentions.0.transformer_blocks.0.attn1",
      "up_blocks.2.attentions.1.transformer_blocks.0.attn1",
      "up_blocks.2.attentions.2.transformer_blocks.0.attn1",
      "up_blocks.3.attentions.0.transformer_blocks.0.attn1",
      "up_blocks.3.attentions.1.transformer_blocks.0.attn1",
      "up_blocks.3.attentions.2.transformer_blocks.0.attn1",
      "mid_block.attentions.0.transformer_blocks.0.attn1",
    ]