dev_run: false
rerun_enabled: false
download_artifacts: false

defaults:
  - multiview_feature_extraction: all
  - generate_video/timesteps: first_half
  - generate_video/layers: encoder_blocks
  - model: stable_diffusion_v1_5

hydra:
  run:
    dir: .
  job:
    chdir: false

wandb:
  run_name: false
  tags: []

inputs:
  sd_seed: 0
  multiview_prompt: "Deadpool"
  animation_prompt: "Deadpool does a backflip"
  unposed_artifact: "backflip:latest"
  animation_artifact: "backflip:latest"

aggregate_3d_features:
  mv_features_artifact_tag: "deadpool-mv-features:latest"
  out_artifact_name: "deadpool-3d-features"
  aggregation_method: "first"
  projection_interp_method: "bilinear"

generate_video:
  vertex_attributes_artifact_tag: "deadpool-3d-features:v6"
  animation_artifact_tag: "backflip:latest"
  out_artifact_name: "deadpool-backflip"
  frame_indices: [1, 2, 3, 4, 5, 6]
  out_resolution: 512
  do_cross_frame_attention: true
  feature_blend_alpha: 0.5
  fps: 10
