dev_run: false
rerun_enabled: false

stable_diffusion:
  name: runwayml/stable-diffusion-v1-5
  torch_dtype: torch.float32

controlnet:
  name: "lllyasviel/control_v11f1p_sd15_depth"

multiview_feature_extraction:
  sd_seed: 0
  animation_artifact_tag: "backflip:latest"
  out_artifact_name: "deadpool-mv-features"
  prompt: "Deadpool does a backflip"
  num_inference_steps: 30
  num_views: 10
  # save_steps: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]
  save_steps: [10]
  module_paths:
    [
      "down_blocks.0.attentions.0.transformer_blocks.0.attn1",
      # "down_blocks.0.attentions.1.transformer_blocks.0.attn1",
      # "down_blocks.1.attentions.0.transformer_blocks.0.attn1",
      # "down_blocks.1.attentions.1.transformer_blocks.0.attn1",
      # "down_blocks.2.attentions.0.transformer_blocks.0.attn1",
      # "down_blocks.2.attentions.1.transformer_blocks.0.attn1",
      # "up_blocks.1.attentions.0.transformer_blocks.0.attn1",
      # "up_blocks.1.attentions.1.transformer_blocks.0.attn1",
      # "up_blocks.1.attentions.2.transformer_blocks.0.attn1",
      # "up_blocks.2.attentions.0.transformer_blocks.0.attn1",
      # "up_blocks.2.attentions.1.transformer_blocks.0.attn1",
      # "up_blocks.2.attentions.2.transformer_blocks.0.attn1",
      # "up_blocks.3.attentions.0.transformer_blocks.0.attn1",
      # "up_blocks.3.attentions.1.transformer_blocks.0.attn1",
      # "up_blocks.3.attentions.2.transformer_blocks.0.attn1",
      # "mid_block.attentions.0.transformer_blocks.0.attn1",
    ]

aggregate_3d_features:
  mv_features_artifact_tag: "deadpool-mv-features:latest"
  out_artifact_name: "deadpool-3d-features"
  aggregation_method: "first"
  projection_interp_method: "bilinear"

generate_video:
  vertex_attributes_artifact_tag: "deadpool-3d-features:latest"
  animation_artifact_tag: "rumba:latest"
  out_artifact_name: "deadpool-backflip"
  frame_indices: [1, 2, 3, 4, 5, 6]
  out_resolution: 512
  prompt: "Deadpool"
  seed: 0
  fps: 10
