defaults:
  - hydra: default
  - run: default
  - model: stable_diffusion_v1_5
  - animation: backflip
  - noise_initialization: uv

run:
  job_type: "generate_video"

prompt: "Deadpool"
out_artifact: "video"

save_tensors:
  enabled: false
  save_latents: true
  n_frames: 5
  out_artifact: 'tensors'

rerun:
  enabled: false
  module_paths: ["down_blocks.0.attentions.0.transformer_blocks.0.attn1"]
  n_frames: 5

generative_rendering:
  resolution: 512
  seed: 0
  do_pre_attn_injection: true
  do_post_attn_injection: true
  feature_blend_alpha: 0.5
  mean_features_weight: 0.5
  chunk_size: 5
  num_keyframes: 8
  attend_to_self_kv: true
  num_inference_steps: 10
  guidance_scale: 7.5
  controlnet_conditioning_scale: 2.0
  module_paths:
    [
      "down_blocks.0.attentions.0.transformer_blocks.0.attn1",
      "down_blocks.0.attentions.1.transformer_blocks.0.attn1",
      "down_blocks.1.attentions.0.transformer_blocks.0.attn1",
      "down_blocks.1.attentions.1.transformer_blocks.0.attn1",
      "down_blocks.2.attentions.0.transformer_blocks.0.attn1",
      "down_blocks.2.attentions.1.transformer_blocks.0.attn1",
      "up_blocks.1.attentions.0.transformer_blocks.0.attn1",
      "up_blocks.1.attentions.1.transformer_blocks.0.attn1",
      "up_blocks.1.attentions.2.transformer_blocks.0.attn1",
      "up_blocks.2.attentions.0.transformer_blocks.0.attn1",
      "up_blocks.2.attentions.1.transformer_blocks.0.attn1",
      "up_blocks.2.attentions.2.transformer_blocks.0.attn1",
      "up_blocks.3.attentions.0.transformer_blocks.0.attn1",
      "up_blocks.3.attentions.1.transformer_blocks.0.attn1",
      "up_blocks.3.attentions.2.transformer_blocks.0.attn1",
      "mid_block.attentions.0.transformer_blocks.0.attn1",
    ]
