hydra:
  run:
    dir: .
  job:
    chdir: false

run:
  job_type: "generate_video"
  wandb: true
  instant_exit: false
  rerun_enabled: false
  download_artifacts: false
  tags: []

model:
  sd_repo: "runwayml/stable-diffusion-v1-5"
  controlnet_repo: "lllyasviel/control_v11f1p_sd15_depth"

inputs:
  animation_artifact_tag: 'backflip:latest'  
  animation_n_frames: 30
  prompt: "Deadpool doing a backflip"
  out_artifact: 'deadpool-backflip'

generative_rendering:
  res: 512
  seed: 0
  num_inference_steps: 40
  do_uv_noise_init: true
  do_pre_attn_injection: true
  do_post_attn_injection: true
  feature_blend_alpha: 1.0
  num_keyframes: 4
  guidance_scale: 7.5
  controlnet_conditioning_scale: 1.0
  chunk_size: 7
  module_paths:
    [
      "down_blocks.0.attentions.0.transformer_blocks.0.attn1",
      "down_blocks.0.attentions.1.transformer_blocks.0.attn1",
      "down_blocks.1.attentions.0.transformer_blocks.0.attn1",
      "down_blocks.1.attentions.1.transformer_blocks.0.attn1",
      "down_blocks.2.attentions.0.transformer_blocks.0.attn1",
      "down_blocks.2.attentions.1.transformer_blocks.0.attn1",
      "up_blocks.1.attentions.0.transformer_blocks.0.attn1",
      "up_blocks.1.attentions.1.transformer_blocks.0.attn1",
      "up_blocks.1.attentions.2.transformer_blocks.0.attn1",
      "up_blocks.2.attentions.0.transformer_blocks.0.attn1",
      "up_blocks.2.attentions.1.transformer_blocks.0.attn1",
      "up_blocks.2.attentions.2.transformer_blocks.0.attn1",
      "up_blocks.3.attentions.0.transformer_blocks.0.attn1",
      "up_blocks.3.attentions.1.transformer_blocks.0.attn1",
      "up_blocks.3.attentions.2.transformer_blocks.0.attn1",
      "mid_block.attentions.0.transformer_blocks.0.attn1",
    ]

