hydra:
  run:
    dir: .
  job:
    chdir: false

defaults:
  - model: stable_diffusion_v1_5
  - animation: backflip

run:
  job_type: "generate_video"
  wandb: true
  instant_exit: false
  download_artifacts: false
  tags: []

prompt: "Deadpool"
out_artifact: "video"

save_tensors:
  enabled: true
  save_latents: true
  n_frames: 5
  out_artifact: 'tensors'

rerun:
  enabled: false
  module_paths: ["down_blocks.0.attentions.0.transformer_blocks.0.attn1"]
  n_frames: 5

generative_rendering:
  res: 512
  seed: 0
  uv_texture_res: 64
  do_uv_noise_init: true
  do_pre_attn_injection: true
  do_post_attn_injection: true
  feature_blend_alpha: 1.0
  mean_features_weight: 0.5
  chunk_size: 5
  num_keyframes: 4
  num_inference_steps: 10
  guidance_scale: 7.5
  controlnet_conditioning_scale: 1.0
  module_paths:
    [
      "down_blocks.0.attentions.0.transformer_blocks.0.attn1",
      "down_blocks.0.attentions.1.transformer_blocks.0.attn1",
      "down_blocks.1.attentions.0.transformer_blocks.0.attn1",
      "down_blocks.1.attentions.1.transformer_blocks.0.attn1",
      "down_blocks.2.attentions.0.transformer_blocks.0.attn1",
      "down_blocks.2.attentions.1.transformer_blocks.0.attn1",
      "up_blocks.1.attentions.0.transformer_blocks.0.attn1",
      "up_blocks.1.attentions.1.transformer_blocks.0.attn1",
      "up_blocks.1.attentions.2.transformer_blocks.0.attn1",
      "up_blocks.2.attentions.0.transformer_blocks.0.attn1",
      "up_blocks.2.attentions.1.transformer_blocks.0.attn1",
      "up_blocks.2.attentions.2.transformer_blocks.0.attn1",
      "up_blocks.3.attentions.0.transformer_blocks.0.attn1",
      "up_blocks.3.attentions.1.transformer_blocks.0.attn1",
      "up_blocks.3.attentions.2.transformer_blocks.0.attn1",
      "mid_block.attentions.0.transformer_blocks.0.attn1",
    ]
