defaults:
  - model: stable_diffusion_v1_5
  - noise_initialization: uv
  - generative_rendering: default

prompt: "Realistic Deadpool, Simple White Background"
animation: { artifact_tag: "rumba:latest", n_frames: 20 }
