- animation_tag: mv_cat_statue_25:latest
  texturing_tag: cat_statue_mv:latest
  src_tag: cat_statue_mv:latest
  prompt: Metalic Cat Statue
  seed: 0
- animation_tag: ymca_20:latest
  texturing_tag: human_mv:latest
  src_tag: ymca_src:latest
  prompt: Stormtrooper
  seed: 0
- animation_tag: ymca_20:latest
  texturing_tag: human_mv:latest
  src_tag: ymca_src:latest
  prompt: Deadpool
  seed: 0
- animation_tag: rumba_20:latest
  texturing_tag: human_mv:latest
  src_tag: rumba_src:latest
  prompt: Stormtrooper
  seed: 0
- animation_tag: catwalk_180_20:latest
  texturing_tag: human_mv:latest
  src_tag: catwalk_180_src:latest
  prompt: Deadpool
  seed: 0
- animation_tag: catwalk_180_20:latest
  texturing_tag: human_mv:latest
  src_tag: catwalk_180_src:latest
  prompt: Deadpool
  seed: 1
- animation_tag: catwalk_180_20:latest
  texturing_tag: human_mv:latest
  src_tag: catwalk_180_src:latest
  prompt: Deadpool
  seed: 2
- animation_tag: mv_helmet_25:latest
  texturing_tag: mv_helmet:latest
  src_tag: mv_helmet:latest
  prompt: Shiny Helmet
  seed: 0
- animation_tag: joyful_jump_20:latest
  texturing_tag: human_mv:latest
  src_tag: joyful_jump_src:latest
  prompt: Stormtrooper
  seed: 0
- animation_tag: joyful_jump_20:latest
  texturing_tag: human_mv:latest
  src_tag: joyful_jump_src:latest
  prompt: Deadpool
  seed: 0
