defaults:
  - model: stable_diffusion_v1_5
  - noise_initialization: uv
  - generative_rendering: default
  - reposable_diffusion: default

scenes: [
    {
      artifact_tag: "handstand:latest",
      n_frames: 20,
      prompt: "Realistic Deadpool, Simple White Background",
    },
    # {
    #   artifact_tag: "rumba:latest",
    #   n_frames: 20,
    #   prompt: "Realistic Deadpool, Simple White Background",
    # },
    # {
    #   artifact_tag: "flair:latest",
    #   n_frames: 20,
    #   prompt: "Realistic Deadpool, Simple White Background",
    # },
    # {
    #   artifact_tag: "backflip:latest",
    #   n_frames: 20,
    #   prompt: "Realistic Deadpool, Simple White Background",
    # },
    # { artifact_tag: "handstand:latest", n_frames: 20, prompt: "Stormtrooper" },
    # { artifact_tag: "handstand:latest", n_frames: 20, prompt: "Abraham Lincoln" },
  ]
