defaults:
  - hydra: default
  - run: default
  - model: stable_diffusion_v1_5
  - noise_initialization: uv
  - reposable_diffusion: default


animation:
  artifact_tag: "booty:latest"
  n_frames: 20

num_views: 10

prompt: "Realistic Deadpool, Simple White Background"
seed: 0
