defaults:
  - hydra: default
  - run: default
  - model: stable_diffusion_v1_5
  - noise_initialization: uv

animation:
  artifact_tag: "booty:latest"
  n_frames: 20

seed: 0
prompt: "Realistic Deadpool, Simple White Background"
out_artifact: "video"

save_tensors:
  enabled: false
  n_frames: 5
  n_timesteps: 5
  out_artifact: "gr_data"
  save_latents: false
  save_q: true
  save_k: true
  save_v: true
  save_kf_post_attn: true
  save_aggregated_features: true
  save_feature_images: true
  module_paths:
    [
      # "down_blocks.0.attentions.0.transformer_blocks.0.attn1",
      # "down_blocks.0.attentions.1.transformer_blocks.0.attn1",
      # "down_blocks.1.attentions.0.transformer_blocks.0.attn1",
      # "down_blocks.1.attentions.1.transformer_blocks.0.attn1",
      # "down_blocks.2.attentions.0.transformer_blocks.0.attn1",
      # "down_blocks.2.attentions.1.transformer_blocks.0.attn1",
      # "mid_block.attentions.0.transformer_blocks.0.attn1",
      "up_blocks.1.attentions.0.transformer_blocks.0.attn1",
      "up_blocks.1.attentions.1.transformer_blocks.0.attn1",
      "up_blocks.1.attentions.2.transformer_blocks.0.attn1",
      "up_blocks.2.attentions.0.transformer_blocks.0.attn1",
      "up_blocks.2.attentions.1.transformer_blocks.0.attn1",
      "up_blocks.2.attentions.2.transformer_blocks.0.attn1",
      "up_blocks.3.attentions.0.transformer_blocks.0.attn1",
      "up_blocks.3.attentions.1.transformer_blocks.0.attn1",
      "up_blocks.3.attentions.2.transformer_blocks.0.attn1",
    ]

generative_rendering:
  attend_to_self_kv: true
  do_pre_attn_injection: true
  do_post_attn_injection: true
  feature_blend_alpha: 1.0
  mean_features_weight: 0.5
  chunk_size: 5
  num_keyframes: 5
  num_inference_steps: 10
  guidance_scale: 7.5
  controlnet_conditioning_scale: 1.0
  module_paths: [
      # "down_blocks.0.attentions.0.transformer_blocks.0.attn1",
      # "down_blocks.0.attentions.1.transformer_blocks.0.attn1",
      # "down_blocks.1.attentions.0.transformer_blocks.0.attn1",
      # "down_blocks.1.attentions.1.transformer_blocks.0.attn1",
      # "down_blocks.2.attentions.0.transformer_blocks.0.attn1",
      # "down_blocks.2.attentions.1.transformer_blocks.0.attn1",
      # "mid_block.attentions.0.transformer_blocks.0.attn1",
      "up_blocks.1.attentions.0.transformer_blocks.0.attn1",
      "up_blocks.1.attentions.1.transformer_blocks.0.attn1",
      "up_blocks.1.attentions.2.transformer_blocks.0.attn1",
      "up_blocks.2.attentions.0.transformer_blocks.0.attn1",
      "up_blocks.2.attentions.1.transformer_blocks.0.attn1",
      "up_blocks.2.attentions.2.transformer_blocks.0.attn1",
      "up_blocks.3.attentions.0.transformer_blocks.0.attn1",
      "up_blocks.3.attentions.1.transformer_blocks.0.attn1",
      "up_blocks.3.attentions.2.transformer_blocks.0.attn1",
    ]
