defaults:
  - hydra: default
  - run: default
  - model: stable_diffusion_v1_5
  - noise_initialization: uv
  - generative_rendering: default

animation:
  artifact_tag: "booty:latest"
  n_frames: 20

seed: 0
prompt: "Realistic Deadpool, Simple White Background"