# @package _global_

run:
  wandb: false
  rerun_enabled: true

inputs:
  animation_n_frames: 10

generative_rendering:
    rerun_module_paths: ["down_blocks.0.attentions.0.transformer_blocks.0.attn1"]
    module_paths: ["down_blocks.0.attentions.0.transformer_blocks.0.attn1"]

